apiVersion: apps/v1
kind: Deployment
metadata:
  name: converter
spec:
  replicas: 4
  selector:
    matchLabels:
      app: converter
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 8
  template:
    metadata:
      labels:
        app: converter
    spec:
      containers:
      - name: converter
        image: edurias/consumer:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        envFrom:
          - configMapRef:
              name: converter-congifmap
          - secretRef:
              name: converter-secret
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: converter-configmap
data:
  MP3_QUEUE: "mp3"
  VIDEO_QUEUE: "video"
---
apiVersion: v1
kind: Secret
metadata:
  name: converter-secret
type: Opaque
stringData:
  PLACEOLDER: "None"


